# Generated by Django 4.1.1 on 2022-09-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='account_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id пользователя'),
        ),
    ]
