# Generated by Django 4.1.1 on 2022-09-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accountdata_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='account_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id пользователя'),
        ),
    ]
