# Generated by Django 4.1.1 on 2022-10-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='event id')),
                ('event_name', models.CharField(blank=True, max_length=150, verbose_name='Event name')),
                ('event_description', models.TextField(blank=True, max_length=1500)),
                ('event_begins', models.DateTimeField(blank=True)),
                ('event_ends', models.DateTimeField(blank=True)),
                ('event_status', models.CharField(blank=True, choices=[('coming', 'Coming soon'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('denied', 'Denied')], max_length=9)),
                ('event_draft', models.BooleanField(blank=True, default=True)),
                ('event_creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
