# Generated by Django 4.1.1 on 2022-10-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_begins',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
