# Generated by Django 4.1.1 on 2022-10-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profiletaglist'),
        ('tags', '0016_alter_tag_tag_creation_date'),
        ('events', '0002_alter_event_event_begins_alter_event_event_ends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_draft',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, default='Draft_event', max_length=150, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('coming', 'Coming soon'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('denied', 'Denied'), ('draft', 'Draft')], default='Draft', max_length=15),
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_status', models.CharField(blank=True, choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='invited', max_length=15)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('profile_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
