version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    container_name: meet2go
    build: .
    command:
              python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/meet2go
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  data: