# Generated by Django 4.1.1 on 2022-09-19 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 22, 24, 52, 816158)),
        ),
    ]
