# Generated by Django 4.1.1 on 2022-09-19 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_tag_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_creation_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 9, 19, 22, 25, 15, 214088)),
        ),
    ]
