# Generated by Django 4.1.1 on 2022-10-01 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(blank=True, verbose_name='Phone number')),
                ('phone_number_countrycode', models.CharField(blank=True, choices=[('Russia', '+7')], max_length=6)),
                ('bio', models.TextField(blank=True, max_length=1500)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender')),
                ('follows', models.ManyToManyField(blank=True, related_name='Followers', to='user_profile.profile')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
